### ISSUE TITLE
四个翻译脚本无法使用，除了搜狗的可以正常运行一下，别的都报错

### ISSUE THREAD

**Issue by ShenYuanOL** [anbangli/PoTranslator#2]

**Comment by anbangli** [comment]
我今天测试了一遍，四个翻译引擎（百度、搜狗、有道和DeepL）都是正常的。

**Comment by WeiKKJ** [comment]
DeepL我这边也不翻译。百度的能用

**Comment by WeiKKJ** [comment]
我在想能不能调用api呢

**Comment by hmirror123** [comment]
我现在也是这个问题，只有搜狗的能用，deepl反馈timeout，其他两个not connect to the tab ;而且翻译的时候输入法老是来回切换

**Comment by KeaiJJ** [comment]
我的也是这个问题，最开始还是ok的，刷了一会就timeout了
