### ISSUE TITLE
在翻译了几百个文本后便无法使用

### ISSUE THREAD

**Issue by ShengGT** [anbangli/PoTranslator#3]
在翻译了几百个文本后便无法使用，就算切换翻译引擎也不行，在翻译过程中会直接卡住，一直显示正在翻译中

**Comment by anbangli** [comment]
换一台计算机使用。或者把文件发给我。

**Comment by KeaiJJ** [comment]
我的也是，翻译了差不多400个左右直接就卡住了，四个翻译引擎都切换是试过，都不行；卸载重新安装了好几次，还是一样，这是什么问题？
