### ISSUE TITLE
我要是想翻译msgstr该怎么办

### ISSUE THREAD

**Issue by Qkvsvh** [anbangli/PoTranslator#4]
如题

**Comment by Qkvsvh** [comment]
@anbangli

**Comment by anbangli** [comment]
我不明白你说的是什么意思。请把问题说得更清楚一些。

**Comment by Qkvsvh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Qkvsvh** [comment]
您好就是翻译已经翻译过的内容

**Comment by Qkvsvh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
